"""Column hired_at is nullable

Revision ID: 7efa17f0cf9f
Revises: 868b6df9597d
Create Date: 2026-05-25 11:23:37.021205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7efa17f0cf9f'
down_revision: Union[str, Sequence[str], None] = '868b6df9597d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'hired_at',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'hired_at',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
