"""Add  unique constraint parent_id-name

Revision ID: 868b6df9597d
Revises: 72aa03211d19
Create Date: 2026-05-25 08:46:28.995212

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '868b6df9597d'
down_revision: Union[str, Sequence[str], None] = '72aa03211d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_department_parent_name', 'departments', ['parent_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_department_parent_name', 'departments', type_='unique')
    # ### end Alembic commands ###
